### ISSUE TITLE
Use of `path.join` for `.location()` URLs

### ISSUE THREAD

**Issue by cklanac** [tomatau/blogful-api#3]
I don't have a windows VM handy to test this, but I think `path.join` will give you backslashes on windows. So using it to join URL segments for `location()` might lead to unexpected results on development compared to production.

```
var filePath = path.join(foo, bar);
// 'foo/bar' on OSX and Linux
// 'foo\\bar' on Windows
```

```
res.status(201).location(path.join(req.originalUrl, user.id)).json(user);
```

**Comment by tomatau** [comment]
omg I'm such a nincompoop yes you're right it should be `url.resolve`, i had express "paths" on the mind >_<

**Comment by cklanac** [comment]
Not sure that will work properly either. It looks like `resolve` appends the root path if given a directory which doesn't begin with `/`, `./` or `../`.
On my box `res.status(201).location(path.resolve('foo', user.id)).json(user);` resolved to...

```
/Users/chris/Code/node-jwt-auth/foo/39f21a4b-d19b-41a8-999b-142d9626fc88
```

The `req.originalUrl` should always start with a `/` so it shouldn't be an issue, but I think it leads the reader down the wrong path (pun intended)

Can we go with string templates ~~or use `url.parse`~~?

**Comment by cklanac** [comment]
Not sure I like the finicky trailing slash treatment. But it's a bit better.

https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost

```
const url = require('url');
url.resolve('/one/two/three', 'four');         // '/one/two/four'
url.resolve('http://example.com/', '/one');    // 'http://example.com/one'
url.resolve('http://example.com/one', '/two'); // 'http://example.com/two'
```

**Comment by tomatau** [comment]
If the `originalUrl` is a trailing `/` consistently then the `url.resolve()` would always work. I actually prefer to redirect to have a consistent trailing slash or not on endpoint paths as well but think it's not in scope for the content.

We can actually use `path.posix.join()` to skirt around the windows path joining as well.

**Comment by tomatau** [comment]
I'm talking about `require('url')` not `require('path')` for the `.resolve()` btw.

The docs don't explain very well that:

```js
url.resolve('/one/two', 'three') === '/one/three'
// but 
url.resolve('/one/two/', 'three') === '/one/two/three' // this is the desired result
```
Can't be sure that the `POST /article` is called with a trailing slash though.

`path.posix.join` should work.. although it'll need a bit of explaining.

**Comment by tomatau** [comment]
Damn your slashes windows! Damn your slashes!
